// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: faculty.sql

package db

import (
	"context"
)

const createFaculty = `-- name: CreateFaculty :one
INSERT INTO faculties (
  name
) VALUES (
  $1
) RETURNING id, name
`

func (q *Queries) CreateFaculty(ctx context.Context, name string) (Faculty, error) {
	row := q.db.QueryRowContext(ctx, createFaculty, name)
	var i Faculty
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
