// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: school.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const countListSchools = `-- name: CountListSchools :one
SELECT COUNT(*)::int FROM schools
`

func (q *Queries) CountListSchools(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countListSchools)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countListSchoolsByName = `-- name: CountListSchoolsByName :one
SELECT COUNT(*)::int FROM schools S
  WHERE $1::varchar ILIKE ANY(S.nick_name)
  OR S.name ILIKE $2::varchar
`

type CountListSchoolsByNameParams struct {
	NickName string `json:"nickName"`
	Name     string `json:"name"`
}

func (q *Queries) CountListSchoolsByName(ctx context.Context, arg CountListSchoolsByNameParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countListSchoolsByName, arg.NickName, arg.Name)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (
  name,
  nick_name,
  city,
  province,
  website,
  email
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateSchoolParams struct {
	Name     string   `json:"name"`
	NickName []string `json:"nickName"`
	City     string   `json:"city"`
	Province string   `json:"province"`
	Website  string   `json:"website"`
	Email    string   `json:"email"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createSchool,
		arg.Name,
		pq.Array(arg.NickName),
		arg.City,
		arg.Province,
		arg.Website,
		arg.Email,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSchoolFacultyAssociation = `-- name: CreateSchoolFacultyAssociation :exec
INSERT INTO school_faculty_associations (
  faculty_id,
  school_id
) VALUES (
  $1, $2
)
`

type CreateSchoolFacultyAssociationParams struct {
	FacultyID int32 `json:"facultyID"`
	SchoolID  int32 `json:"schoolID"`
}

func (q *Queries) CreateSchoolFacultyAssociation(ctx context.Context, arg CreateSchoolFacultyAssociationParams) error {
	_, err := q.db.ExecContext(ctx, createSchoolFacultyAssociation, arg.FacultyID, arg.SchoolID)
	return err
}

const getSchoolInfo = `-- name: GetSchoolInfo :one
SELECT
  S.name,
  COALESCE(ROUND(AVG(SR.reputation), 1), 0.0)::varchar as reputation,
  COALESCE(ROUND(AVG(SR.location), 1), 0.0)::varchar as location,
  COALESCE(ROUND(AVG(SR.opportunities), 1), 0.0)::varchar as opportunities,
  COALESCE(ROUND(AVG(SR.facilities), 1), 0.0)::varchar as facilities,
  COALESCE(ROUND(AVG(SR.internet), 1), 0.0)::varchar as internet,
  COALESCE(ROUND(AVG(SR.food), 1), 0.0)::varchar as food,
  COALESCE(ROUND(AVG(SR.clubs), 1), 0.0)::varchar as clubs,
  COALESCE(ROUND(AVG(SR.social), 1), 0.0)::varchar as social,
  COALESCE(ROUND(AVG(SR.happiness), 1), 0.0)::varchar as happiness,
  COALESCE(ROUND(AVG(SR.safety), 1), 0.0)::varchar as safety,
  COALESCE(ROUND(AVG(SR.overall_rating), 1), 0.0)::varchar as overall_rating
FROM schools S
  LEFT JOIN school_ratings SR ON S.id = SR.school_id
WHERE
  S.id = $1
GROUP BY S.id
`

type GetSchoolInfoRow struct {
	Name          string `json:"name"`
	Reputation    string `json:"reputation"`
	Location      string `json:"location"`
	Opportunities string `json:"opportunities"`
	Facilities    string `json:"facilities"`
	Internet      string `json:"internet"`
	Food          string `json:"food"`
	Clubs         string `json:"clubs"`
	Social        string `json:"social"`
	Happiness     string `json:"happiness"`
	Safety        string `json:"safety"`
	OverallRating string `json:"overallRating"`
}

func (q *Queries) GetSchoolInfo(ctx context.Context, id int32) (GetSchoolInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getSchoolInfo, id)
	var i GetSchoolInfoRow
	err := row.Scan(
		&i.Name,
		&i.Reputation,
		&i.Location,
		&i.Opportunities,
		&i.Facilities,
		&i.Internet,
		&i.Food,
		&i.Clubs,
		&i.Social,
		&i.Happiness,
		&i.Safety,
		&i.OverallRating,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT
  S.id,
  S.name,
  S.city,
  S.province
FROM schools S
ORDER BY
  CASE
    WHEN $3::varchar = 'name' AND $4::varchar = 'asc' THEN LOWER(S.name)
    ELSE NULL
  END,
  CASE
    WHEN $3::varchar = 'name' AND $4::varchar = 'desc' THEN LOWER(S.name)
    ELSE NULL
  END DESC
LIMIT $1
OFFSET $2
`

type ListSchoolsParams struct {
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
	SortBy    string `json:"sortBy"`
	SortOrder string `json:"sortOrder"`
}

type ListSchoolsRow struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	City     string `json:"city"`
	Province string `json:"province"`
}

func (q *Queries) ListSchools(ctx context.Context, arg ListSchoolsParams) ([]ListSchoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchools,
		arg.Limit,
		arg.Offset,
		arg.SortBy,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchoolsRow{}
	for rows.Next() {
		var i ListSchoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Province,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByName = `-- name: ListSchoolsByName :many
SELECT
  S.id,
  S.name,
  S.city,
  S.province
FROM schools S
WHERE $3::varchar ILIKE ANY(S.nick_name) OR S.name ILIKE $4::varchar
ORDER BY
  CASE
    WHEN $5::varchar = 'name' AND $6::varchar = 'asc' THEN LOWER(S.name)
    ELSE NULL
  END,
  CASE
    WHEN $5::varchar = 'name' AND $6::varchar = 'desc' THEN LOWER(S.name)
    ELSE NULL
  END DESC
LIMIT $1
OFFSET $2
`

type ListSchoolsByNameParams struct {
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
	NickName  string `json:"nickName"`
	Name      string `json:"name"`
	SortBy    string `json:"sortBy"`
	SortOrder string `json:"sortOrder"`
}

type ListSchoolsByNameRow struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	City     string `json:"city"`
	Province string `json:"province"`
}

func (q *Queries) ListSchoolsByName(ctx context.Context, arg ListSchoolsByNameParams) ([]ListSchoolsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsByName,
		arg.Limit,
		arg.Offset,
		arg.NickName,
		arg.Name,
		arg.SortBy,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchoolsByNameRow{}
	for rows.Next() {
		var i ListSchoolsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Province,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomSchoolID = `-- name: RandomSchoolID :one
SELECT id FROM schools
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) RandomSchoolID(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, randomSchoolID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateSchoolStatusRequest = `-- name: UpdateSchoolStatusRequest :one
UPDATE schools
SET
  status = $1
WHERE
  id = $2::int
RETURNING id, name, nick_name, country, city, province, website, email, status, verified_date
`

type UpdateSchoolStatusRequestParams struct {
	Status Statusrequest `json:"status"`
	ID     int32         `json:"id"`
}

func (q *Queries) UpdateSchoolStatusRequest(ctx context.Context, arg UpdateSchoolStatusRequestParams) (School, error) {
	row := q.db.QueryRowContext(ctx, updateSchoolStatusRequest, arg.Status, arg.ID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.NickName),
		&i.Country,
		&i.City,
		&i.Province,
		&i.Website,
		&i.Email,
		&i.Status,
		&i.VerifiedDate,
	)
	return i, err
}
