// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: school.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (
  name,
  country,
  province,
  website,
  email
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, nick_name, country, province, website, email, status, verified_date
`

type CreateSchoolParams struct {
	Name     string `json:"name"`
	Country  string `json:"country"`
	Province string `json:"province"`
	Website  string `json:"website"`
	Email    string `json:"email"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRowContext(ctx, createSchool,
		arg.Name,
		arg.Country,
		arg.Province,
		arg.Website,
		arg.Email,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.NickName),
		&i.Country,
		&i.Province,
		&i.Website,
		&i.Email,
		&i.Status,
		&i.VerifiedDate,
	)
	return i, err
}

const getSchool = `-- name: GetSchool :one
SELECT id, name, nick_name, country, province, website, email, status, verified_date FROM schools
WHERE id = $1
`

func (q *Queries) GetSchool(ctx context.Context, id int64) (School, error) {
	row := q.db.QueryRowContext(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.NickName),
		&i.Country,
		&i.Province,
		&i.Website,
		&i.Email,
		&i.Status,
		&i.VerifiedDate,
	)
	return i, err
}

const getSchoolInfoAggregate = `-- name: GetSchoolInfoAggregate :one
SELECT
  AVG(SR.reputation)::smallint as reputation,
  AVG(SR.location)::smallint as location,
  AVG(SR.opportunities)::smallint as opportunities,
  AVG(SR.facilities)::smallint as facilities,
  AVG(SR.internet)::smallint as internet,
  AVG(SR.food)::smallint as food,
  AVG(SR.clubs)::smallint as clubs,
  AVG(SR.social)::smallint as social,
  AVG(SR.happiness)::smallint as happiness,
  AVG(SR.safety)::smallint as safety,
  AVG(SR.overall_rating)::smallint as overall_rating
FROM schools S
  JOIN school_ratings SR ON S.id = SR.school_id
WHERE
  S.id = $1
GROUP BY S.id
`

type GetSchoolInfoAggregateRow struct {
	Reputation    int16 `json:"reputation"`
	Location      int16 `json:"location"`
	Opportunities int16 `json:"opportunities"`
	Facilities    int16 `json:"facilities"`
	Internet      int16 `json:"internet"`
	Food          int16 `json:"food"`
	Clubs         int16 `json:"clubs"`
	Social        int16 `json:"social"`
	Happiness     int16 `json:"happiness"`
	Safety        int16 `json:"safety"`
	OverallRating int16 `json:"overall_rating"`
}

func (q *Queries) GetSchoolInfoAggregate(ctx context.Context, id int64) (GetSchoolInfoAggregateRow, error) {
	row := q.db.QueryRowContext(ctx, getSchoolInfoAggregate, id)
	var i GetSchoolInfoAggregateRow
	err := row.Scan(
		&i.Reputation,
		&i.Location,
		&i.Opportunities,
		&i.Facilities,
		&i.Internet,
		&i.Food,
		&i.Clubs,
		&i.Social,
		&i.Happiness,
		&i.Safety,
		&i.OverallRating,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, nick_name, country, province, website, email, status, verified_date FROM schools
LIMIT $1
OFFSET $2
`

type ListSchoolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSchools(ctx context.Context, arg ListSchoolsParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			pq.Array(&i.NickName),
			&i.Country,
			&i.Province,
			&i.Website,
			&i.Email,
			&i.Status,
			&i.VerifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSchoolsByNameOrNickName = `-- name: SearchSchoolsByNameOrNickName :many
SELECT id, name, nick_name, country, province, website, email, status, verified_date FROM schools
WHERE name LIKE $1 OR $1 LIKE ANY(nick_name)
LIMIT 10
`

func (q *Queries) SearchSchoolsByNameOrNickName(ctx context.Context, name string) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, searchSchoolsByNameOrNickName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			pq.Array(&i.NickName),
			&i.Country,
			&i.Province,
			&i.Website,
			&i.Email,
			&i.Status,
			&i.VerifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchoolStatusRequest = `-- name: UpdateSchoolStatusRequest :one
UPDATE schools
SET
  status = $1::text
WHERE
  id = $2::bigint
RETURNING id, name, nick_name, country, province, website, email, status, verified_date
`

type UpdateSchoolStatusRequestParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateSchoolStatusRequest(ctx context.Context, arg UpdateSchoolStatusRequestParams) (School, error) {
	row := q.db.QueryRowContext(ctx, updateSchoolStatusRequest, arg.Status, arg.ID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.NickName),
		&i.Country,
		&i.Province,
		&i.Website,
		&i.Email,
		&i.Status,
		&i.VerifiedDate,
	)
	return i, err
}
