// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: tag.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
  name
) VALUES (
  $1
) RETURNING name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	err := row.Scan(&name)
	return name, err
}

const randomTag = `-- name: RandomTag :one
SELECT name FROM tags
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) RandomTag(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, randomTag)
	var name string
	err := row.Scan(&name)
	return name, err
}
